### ISSUE TITLE
Hipchat does not show up in Graylog2 outputs

### ISSUE THREAD

**Issue by jyotiruhil** [Graylog2/graylog-plugin-hipchat#11]
I downloaded the .jar file and placed in the plugin directory. I did the same thing for Slack plugin. But hipchat does not show up in the output list like Slack. But it is available in the alert callback. 

Please let me know whether I am missing something. 

<img width="362" alt="screen shot 2016-07-28 at 11 20 42 pm" src="https://cloud.githubusercontent.com/assets/7250451/17240312/8579ccbe-551f-11e6-93e5-a78dbeae1c8b.png">

Here is the screenshot of Alert callback list:
<img width="305" alt="screen shot 2016-07-29 at 12 01 13 am" src="https://cloud.githubusercontent.com/assets/7250451/17240337/b1f669f0-551f-11e6-9156-32a3d20a32e6.png">

**Comment by joschi** [comment]
@jyotiruhil This plugin only contains a HipChat alarm callback (see http://docs.graylog.org/en/2.0/pages/streams.html#alert-callbacks-types-explained) and no message output.
