### ISSUE TITLE
Consider providing a jar file for easy deployment

### ISSUE THREAD

**Issue by nlochschmidt** [Graylog2/graylog-plugin-hipchat#2]
Thanks for bringing this plugin back :smiley: 
Do you have any plans to provide a packaged version released alongside the graylog2 distribution? It would really help us with upgrading graylog2 on a chef-managed server.

**Comment by joschi** [comment]
The JAR files are now available in the GitHub releases for this repository: https://github.com/Graylog2/graylog-plugin-hipchat/releases
