### ISSUE TITLE
How to configure and use this plugin? 

### ISSUE THREAD

**Issue by romanr** [Graylog2/graylog-plugin-hipchat#9]
How to configure and use this plugin ? Where do you set Alarm Callback? 

I searched official Graylog documentation, and only mention is on this page http://docs.graylog.org/en/2.0/pages/plugins.html?highlight=alarm%20callback :

> Alarm  Callbacks: Called when a stream alert condition has been triggered

That's it. Figure it out.
I checked all screens in Graylog web UI and couldn't find any place where such option appears.
Any hint what to do please?

**Comment by mariussturm** [comment]
Alarm callbacks are used as part of the Stream system: http://docs.graylog.org/en/2.0/pages/streams.html#alerts

**Comment by mariussturm** [comment]
We use Github to track actual bugs, please use or community channels for general questions. Thanks!
